// AUTO-GENERATED by scripts/gen-charm-sprite.mjs — a small isolated ASCII
// sprite of "the charm" (downsampled from charmFrames[0]), used by ScrollCharm
// as a flying mascot that traverses the page on scroll.
export const charmSpriteCols = 17;
export const charmSpriteRows = 5;
export const charmSprite = "             .   \n  -%*.   *%*##.  \n #@@@- -*@%%%#%*.\n:@@@@*+%@@%@@@#+*\n  -+#%@#@@@@@%-. ";
